default: &default
    adapter: postgresql
    encoding: unicode
    max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: sample_app_development
    url: <%= ENV["DATABASE_URL_DEVELOPMENT"] %>

test:
    <<: *default
    database: sample_app_test
    url: <%= ENV["DATABASE_URL_TEST"] %>


production:
    primary: &primary_production
        <<: *default
        url: <%= ENV["DATABASE_URL"] %>
        sslmode: require

    cache:
        <<: *primary_production
    queue:
        <<: *primary_production
    cable:
        <<: *primary_production
